#!/bin/bash

##############################################################
# Original Author:  Evan Ng, 2013                            #
#                                                            #
# Don't forget to change the locale of your search engines   #
# to ones you to the correct locale that you are in.         #
# i.e:   google.co.uk, ebay.se, etc                          #
#                                                            #
##############################################################
#definitions
browser="firefox"
google="http://www.google.ca/search?q="
reddit="reddit.com/search?q="
ebay="www.ebay.ca/sch/items/"
ddg="https://www.duckduckgo.com/?q="
wiki="en.wikipedia.org/wiki/"
youtube="https://www.youtube.com/results?search_query="

# search Engine can be one of g, y, d, e, b, w
# ${1} pulls out only the first argument
searchEngine=${1}

# query is the searchEngine letter AND the search terms
# i.e.   "g sennheiser headphones"
query=${@}

# searchTerms is the search terms isolated:
# i.e.  "sennheiser headphones"
searchTerms=${query:${#searchEngine}}

# stformatted is the search terms with "+" placed in between
# space; since we all know how browsers hate spaces.
# i.e. "sennheiser+headphones"
stformatted=$(echo $searchTerms | sed 's/ /+/g')

if [ ${#searchEngine} == 1 ]; then
    if [[ "$searchEngine" != "g" && "$searchEngine" != "y" &&
        "$searchEngine" != "d" && "$searchEngine" != "w" &&
        "$searchEngine" != "e" && "$searchEngine" != "r" ]];
    then
        echo "not a valid defined search engine"
    else
        case $searchEngine in
        g)
            #echo "google"
            #echo "${google}$stformatted"
            $browser "${google}$stformatted"
            ;;
        "y")
            #echo "youtube"
            #echo "${youtube}$stformatted"
            $browser "${youtube}$stformatted"
            ;;
        "d")
            #echo "duck duck go"
            #echo $stformatted
            #echo "${ddg}$stformatted"
            $browser "${ddg}$stformatted"
            ;;
        "w")
            #echo "wikipedia"
            # wiki string format is a little different:
            # i.e.   "sennheiser_headphones"
            wikistring=$(echo $searchTerms | sed 's/ /_/g')
            #echo $wikistring
            #echo "${wiki}$wikistring"
            $browser "${wiki}$wikistring"
            ;;
        "e")
            #echo "ebay"
            #echo $stformatted
            #echo "${ebay}$stformatted"
            $browser "${ebay}$stformatted"
            ;;
        "r")
            #echo "reddit"
            #echo $stformatted
            #echo "${reddit}$stformatted"
            $browser "${reddit}$stformatted"
            ;;
        *)
            echo "invalid search engine type, please try again"
            ;;
        esac
    fi
else
    #this is the case when the searchEngine is more than a letter or not letters
    echo "search engine field parameter either too long, or empty"
fi
